### ISSUE TITLE
css 绘制三角形和箭头

### ISSUE THREAD

**Issue by zhaofeihao** [zhaofeihao/ZNotes#6]
### 三角形
在某些下拉框需求中会有下拉框收起时三角形朝下显示，下拉框弹出时三角形朝上显示。

<img width="142" alt="down" src="https://user-images.githubusercontent.com/33317030/65381200-21a99f80-dd1f-11e9-992a-5cb079bb2f3e.png">

![image](https://user-images.githubusercontent.com/33317030/65381203-338b4280-dd1f-11e9-949f-90b1d6a0bbcc.png)

--------------------

这时可以通过 CSS 绘制该简单图形，通过切换类名达到切换显示效果。

具体实现：
``` css
.down {
        width: 0px;
        height: 0px;
        border-top: 10px solid #ccc;
        border-left: 10px solid transparent;
        border-right: 10px solid transparent;
}

.up {
       width: 0px;
       height: 0px;
       border-bottom: 10px solid #ccc;
       border-left: 10px solid transparent;
       border-right: 10px solid transparent;
}
```

### 箭头
箭头其实就是2个三角形，然后用白色三角形覆盖蓝色三角形，并且错开1px，刚刚好就形成了箭头。
左箭头：
``` css
.left{
    position: absolute;
}
.left:before,.left:after{
    position: absolute;
    content: '';
    border-top: 10px transparent dashed;
    border-left: 10px transparent dashed;
    border-bottom: 10px transparent dashed;
    border-right: 10px #fff solid;
}
.left:before{
    border-right: 10px #0099CC solid;
}
.left:after{
    left: 1px; /*覆盖并错开1px*/
    border-right: 10px #fff solid;
}
```
<img width="91" alt="left" src="https://user-images.githubusercontent.com/33317030/65381305-e6a86b80-dd20-11e9-8cc9-d296f4911e27.png">

上箭头：
``` css
.top{
    position: absolute;
}
.top:before,.top:after{
    position: absolute;
    content: '';
    border-top: 10px transparent dashed;
    border-left: 10px transparent dashed;
    border-right: 10px transparent dashed;
    border-bottom: 10px #fff solid;
}
.top:before{
    border-bottom: 10px #0099CC solid;
}
.top:after{
    top: 1px; /*覆盖并错开1px*/
    border-bottom: 10px #fff solid;
}
```
<img width="100" alt="top" src="https://user-images.githubusercontent.com/33317030/65381306-ec9e4c80-dd20-11e9-84e5-fbcb66be1662.png">

最后可以通过 `transform:rotate(90deg)` 来搞定其他方向。
